[package]
name = "ochra-oracle"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
ochra-types = { path = "../ochra-types" }
thiserror.workspace = true
serde.workspace = true
tracing.workspace = true
